Repository parlamentaqui/frontend, pull requests merged in 2021-05, with the labels that each got.

#98 86 tela lista deputados
  package-lock.json
  package.json
  src/Api.js
  src/components/ActivityListItem/index.css
  src/components/ActivityListItem/index.js
  src/components/DeputiesList/DeputiesList.js
  src/components/DeputiesList/index.css
  src/components/DeputiesList/index.js
  src/components/HomeNews/index.css
  src/components/HomeNews/index.js
  src/components/ImageDeputiesList/index.css
  src/components/ImageDeputiesList/index.js
  src/components/News/NewsMobile.css
  src/components/Profile/Profile.css
  src/components/Profile/Profile.js
  src/components/Profile/ProfileMobile.css
  src/components/TopBar/index.css
  src/components/TopBar/index.js
  src/components/Tweet/index.css
  src/images/search-icon.svg
  src/index.css
  src/screens/DeputiesScreen.js
  src/screens/SearchScreen.js
Labels: EASY, FEATURE, MDS, US

#99 Fix #87 componente proposicao deputado
  package-lock.json
  package.json
  src/Api.js
  src/components/AuthoredPropositions/AuthoredPropositionMobile.css
  src/components/AuthoredPropositions/AuthoredPropositionMobile.js
  src/components/AuthoredPropositions/index.css
  src/components/AuthoredPropositions/index.js
  src/components/TopBar/index.js
  src/images/light-bulb.svg
  src/images/ocultar.png
  src/images/seta.png
  src/screens/DeputyProfileScreen/index.js
Labels: FEATURE, MDS, MEDIUM, US

#110 FIX #101 curiosidade alinhamento governo
  public/favicon.ico
  src/App.js
  src/components/ActivityListProposition/index.js
  src/components/AuthoredPropositions/AuthoredPropositionMobile.js
  src/components/AuthoredPropositions/index.css
  src/components/AuthoredPropositions/index.js
  src/components/Breadcrumbs/index.js
  src/components/DataVoting/DataVoting.js
  src/components/News/News.js
  src/components/News/NewsMobile.js
  src/components/Profile/Profile.css
  src/components/Profile/Profile.js
  src/components/Profile/ProfileMobile.css
  src/components/Profile/ProfileMobile.js
  src/components/ProjectsList/index.js
  src/components/Proposition/Proposition.js
  src/components/Proposition/PropositionsMobile.js
  src/components/SearchFilterProposition/index.css
  src/components/SearchFilterProposition/index.js
  src/components/ShareButton/index.css
  src/components/ShareButton/index.js
  yarn.lock
Labels: FEATURE, HOTFIX, MDS, MEDIUM, US
