Repository parlamentaqui/frontend, pull requests merged in 2021-04, with the labels that each got.

#50 Fix #33 Projetos votados
  src/Api.js
  src/App.js
  src/components/DataVoting/DataVoting.css
  src/components/DataVoting/DataVoting.js
  src/components/DataVoting/DataVotingMobile.js
  src/components/DataVoting/Vote.js
  src/components/HomeNews/index.css
  src/components/HomeNews/index.js
  src/components/News/News.css
  src/components/News/News.js
  src/components/News/NewsMobile.css
  src/components/News/NewsMobile.js
  src/components/Profile/Profile.js
  src/components/Profile/ProfileMobile.js
  src/components/SearchHome/index.css
  src/components/SearchHome/index.js
  src/images/icon-cancela-red.png
  src/images/icon-confirma-black.png
  src/screens/DeputyProfileScreen.js
  src/screens/DeputyProfileScreen/index.js
  src/screens/HomeScreen/index.js
Labels: FEATURE, HARD, MDS, US

#54 30 compartilhar news deputado
  src/components/News/News.js
  src/components/News/NewsMobile.js
Labels: EASY, FEATURE, MDS, US

#65 HOTFIX #62 Breadcrumb das telas atuais consertadas
  .gitignore
  src/components/Breadcrumbs/index.js
  src/components/Breadcrumbs/tests/__snapshots__/breadcrumbs.test.js.snap
  src/components/Breadcrumbs/tests/breadcrumbs.test.js
  src/components/DataVoting/DataVoting.js
  src/components/News/News.js
Labels: HARD, HOTFIX, MDS
